# This file was generated for CI/CD purposes
# Simplified version of default.nix without RStudio wrapper
# Based on default.nix generated by {rix} v0.17.2
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-05.tar.gz") {};

  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages)
      bslib
      covr
      devtools
      dplyr
      DT
      ggplot2
      htmlwidgets
      knitr
      pkgload
      plotly
      purrr
      quarto
      rmarkdown
      scales
      shiny
      shinylive
      tarchetypes
      targets
      testthat
      tidyr;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R
      pandoc
      which;
  };
 
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
