# This file was generated by the {rix} R package v0.17.4 on 2026-02-19
# with following call:
# >rix(date = "2026-01-05",
#  > r_pkgs = r_packages,
#  > system_pkgs = NULL,
#  > git_pkgs = gh_pkgs,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-05.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      bslib
      covr
      devtools
      dplyr
      DT
      ggplot2
      gt
      htmlwidgets
      knitr
      pkgload
      plotly
      purrr
      quarto
      rmarkdown
      scales
      shiny
      shinylive
      tarchetypes
      targets
      testthat
      tidyr;
  };
 
    rwasm = (pkgs.rPackages.buildRPackage {
      name = "rwasm";
      src = pkgs.fetchgit {
        url = "https://github.com/r-wasm/rwasm";
        rev = "ebd68f7a1eb3378dfc968dd7ddcd3f412c34e8bb";
        sha256 = "sha256-nhJlXhNkMOEI0RFo0FMxeS9Cd0caXMYiUz2+7Iswnag=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          dplyr
          fs
          jsonlite
          lifecycle
          pak
          pkgdepends
          rlang
          withr
          zip;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R
      quarto
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rwasm rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
